#!/bin/bash
FILES=(
  "src/app/api/cli-tools/openclaw-settings/route.ts"
  "src/app/api/cli-tools/codex-profiles/route.ts"
  "src/app/api/cli-tools/letta-settings/route.ts"
  "src/app/api/cli-tools/deepseek-tui-settings/route.ts"
  "src/app/api/cli-tools/guide-settings/[toolId]/route.ts"
  "src/app/api/cli-tools/codewhale-settings/route.ts"
  "src/app/api/cli-tools/codex-settings/route.ts"
  "src/app/api/cli-tools/forge-settings/route.ts"
  "src/app/api/cli-tools/pi-settings/route.ts"
  "src/app/api/cli-tools/kilo-settings/route.ts"
  "src/app/api/cli-tools/droid-settings/route.ts"
  "src/app/api/cli-tools/crush-settings/route.ts"
  "src/app/api/cli-tools/hermes-agent-settings/route.ts"
  "src/app/api/cli-tools/cline-settings/route.ts"
  "src/app/api/cli-tools/jcode-settings/route.ts"
  "src/app/api/cli-tools/omp-settings/route.ts"
  "src/app/api/cli-tools/claude-settings/route.ts"
  "src/app/api/cli-tools/qwen-settings/route.ts"
  "src/app/api/cli-tools/smelt-settings/route.ts"
  "src/app/api/cli-tools/all-statuses/route.ts"
  "src/app/api/cli-tools/grok-build-settings/route.ts"
  "src/app/api/providers/agy-auth/apply-local/route.ts"
  "src/lib/cloudflaredTunnel.ts"
  "src/lib/tailscaleTunnel.ts"
  "src/lib/dataPaths.ts"
  "src/lib/db/core.ts"
  "src/lib/db/backup.ts"
  "src/lib/db/databaseSettings.ts"
  "src/lib/db/backupRetention.ts"
  "src/lib/db/probeUtils.ts"
  "src/lib/db/migrationRunner.ts"
  "src/lib/db/adapters/nodeSqliteShared.ts"
  "src/lib/db/adapters/bunSqliteAdapter.ts"
  "src/lib/db/adapters/sqljsAdapter.ts"
  "src/lib/db/migrationRunner/extraDirs.ts"
  "src/lib/zed-oauth/dockerDetect.ts"
  "src/lib/services/ringBuffer.ts"
  "src/lib/services/installers/cliproxy.ts"
  "src/lib/services/installers/bifrost.ts"
  "src/lib/services/installers/ninerouter.ts"
  "src/lib/config/hotReload.ts"
  "src/lib/services/installers/mux.ts"
  "src/lib/services/installers/dario.ts"
  "src/lib/catalog/openrouterCatalog.ts"
  "src/lib/skills/builtins.ts"
  "src/lib/usage/callLogArtifacts.ts"
  "src/lib/usage/callLogs.ts"
  "src/lib/usage/migrations.ts"
  "src/lib/catalog/openrouterProviderStats.ts"
  "src/lib/cliTools/checkToolConfigStatus.ts"
  "src/lib/versionManager/processManager.ts"
  "src/lib/versionManager/binaryManager.ts"
  "src/lib/memory/embedding/staticPotion.ts"
  "src/lib/usage/callLogRotation.ts"
  "src/lib/usage/callLogArtifactWriter.ts"
  "src/lib/oauth/utils/codexAuthFile.ts"
  "src/lib/oauth/utils/claudeAuthFile.ts"
  "src/lib/monitoring/buildSha.ts"
  "src/lib/agentSkills/catalog.ts"
  "src/lib/agentSkills/openapiParser.ts"
  "src/lib/agentSkills/generator.ts"
  "src/lib/cli-helper/config-generator/codex.ts"
  "src/lib/cli-helper/config-generator/opencode.ts"
  "src/lib/oauth/providers/kimi-coding.ts"
  "src/lib/headroom/process.ts"
  "src/lib/agentSkills/cliRegistryParser.ts"
  "src/lib/localCorpus/index.ts"
  "src/lib/obsidianSync.ts"
  "src/app/api/cli-tools/apply/route.ts"
)

for file in "${FILES[@]}"; do
  if [ -f "$file" ]; then
    # Standard replacement: fs from "fs/promises" -> * as fsNative from "fs", fs = fsNative.promises
    sed -i 's/import fs from "fs\/promises";/import * as fsNative from "fs";\nconst fs = fsNative.promises;/g' "$file"
    sed -i 's/import fs from "node:fs\/promises";/import * as fsNative from "node:fs";\nconst fs = fsNative.promises;/g' "$file"

    # Sync versions
    sed -i 's/import fs from "fs";/import * as fs from "fs";/g' "$file"
    sed -i 's/import fs from "node:fs";/import * as fs from "node:fs";/g' "$file"

    # Special case where it's already named something else like fsPromises
    sed -i 's/import fsPromises from "fs\/promises";/import * as fsNative from "fs";\nconst fsPromises = fsNative.promises;/g' "$file"
  fi
done
